apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xeksclusters.aws.informatica.com
spec:
  group: aws.informatica.com
  names:
    kind: XEKSCluster
    plural: xeksclusters
  claimNames:
    kind: EKSCluster
    plural: eksclusters
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              name:
                type: string 
                description: cluster name
              region:
                type: string
                description: cluster region
              public:
                type: string
                description: whether cluster endpoint should be exposed publicly
                enum:
                  - "true"
                  - "false"
              env:
                type: string
                description: cluster environment
                enum:
                  - qa
                  - prod
                  - dev
              org:
                type: object
                properties:
                  be:
                    type: string 
                    description: business entity
                  bu:
                    type: string 
                    description: business unit
                required:
                  - be
                  - bu
              tags:
                type: object
                properties:
                  ownerEmail:
                    type: string 
                    description: emailid of the resource creator
                required:
                  - ownerEmail
            required:
              - name
              - region
              - public
              - env
              - org
              - tags