apiVersion: s3.aws.upbound.io/v1beta1
kind: Bucket
metadata:
  annotations:
    crossplane.io/external-name: nang-cp-bucket
  name: nang-cp-bucket
spec:
  forProvider:
    region: us-west-2
    tags:
      newTag: "true"